Patvin_Live/MvcApplication1/Models/AddNewPage.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Patvin.Models
{
    public class AddNewPage
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "PageName is required.")]
        public string PageName { get; set; }

        [Required(ErrorMessage = "Banner Image is required.")]
        public string BannerImage { get; set; }

        [Required(ErrorMessage = "Description is required.")]
        public string Description { get; set; }

        public string imgPreview { get; set; }

        public string Sr { get; set; }
        public List<AddNewPage> NewPageList { get; set; }

        public string Slug { get; set; }

        public string Img_Alt_Tag { get; set; }

    }
}

Patvin_Live/MvcApplication1/Models/ApplyForJob.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Patvin.Models
{
    public class ApplyForJob
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Name is required.")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Email address is required.")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "Invalid email address.")]
        public string Email { get; set; }
 
        public string Role { get; set; }
        public string Location { get; set; }


        [Required(ErrorMessage = "mobile number is required.")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression("^[0 - 9]{10}$|^[0-9]{10,12}$", ErrorMessage = "Enter a valid mobile number.")]

        public string ContactNo { get; set; }

        [Required(ErrorMessage = "Resume is required.")]
        [RegularExpression(@"([a-zA-Z0-9\s_\\.\-:])+(.doc|.docx|.pdf)$", ErrorMessage = "Only Document files allowed.")]
        public string Resume { get; set; }

        public string ApplyDate { get; set; }

        public string Sr { get; set; }

        public List<ApplyForJob> ApplyForJobList { get; set; }


        public string fakePath { get; set; }
    }
}

Patvin_Live/MvcApplication1/Models/CMS.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Patvin.Models
{
    public class CMS
    {
        public int CmsId { get; set; }

        public string Heading { get; set; }

        public string Description { get; set; }

        public List<CMS> CMSList { get; set; }
    }
}

Patvin_Live/MvcApplication1/Models/CareerOurPeople.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Patvin.Models
{
    public class CareerOurPeople
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Name is Required.")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Position is Required.")]
        public string Position { get; set; }

        [Required(ErrorMessage = "Description is Required ")]
        public string Description { get; set; }

        public int DisplayOrder { get; set; }

        [Required(ErrorMessage = "Image is required.")]

        public string Image { get; set; }

        public List<CareerOurPeople> CareerOurPeopleList { get; set; }

        public string Sr { get; set; }

        public string imgPreview { get; set; }

        public string Img_Alt_Tag { get; set; }
    }
}

Patvin_Live/MvcApplication1/Models/CareerOverViewImages.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Patvin.Models
{
    public class CareerOverViewImages
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Image is required.")]

        public string Image { get; set; }

        public List<CareerOverViewImages> CareerOverViewImagesList { get; set; }

        public int DisplayOrder { get; set; }

        public string Sr { get; set; }

        public string imgPreview { get; set; }

        public string Img_Alt_Tag { get; set; }
    }
}

Patvin_Live/MvcApplication1/Models/CareerWeBelieve.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Patvin.Models
{
    public class CareerWeBelieve
    {
        public int Id { get; set; }

        public string Description { get; set; }

        public List<CareerWeBelieve>CareerWeBelieveList {get;set;}

        public string Sr { get; set; }
    }
}

Patvin_Live/MvcApplication1/Models/CaseStudies.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Patvin.Models
{
    public class CaseStudies
    {
        public int Id { get; set; }

        [Required (ErrorMessage ="Image is required")]
        public string Image { get; set; }

        [Required(ErrorMessage = "Heading is required")]
        public string Heading { get; set; }

        [Required(ErrorMessage = "Category is required")]
        public string Category { get; set; }

        public string imgPreview { get; set; }
        
        public int DisplayOrder { get; set; }

        public string Sr { get; set; }

        public List<CaseStudies> CaseStudiesList { get; set; }

        public string Img_Alt_Tag { get; set; }
        

    }
}

Patvin_Live/MvcApplication1/Models/ContactMap.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Patvin.Models
{
    public class ContactMap
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Title is require")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Description is require")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Latitude is require")]
        public string Latitude { get; set; }

        [Required(ErrorMessage = "Longitude is require")]
        public string Longitude { get; set; }

        [Required(ErrorMessage = "Icon is require")]
        public string Image { get; set; }

        public string imgPreview { get; set; }

        public List<ContactMap> ContactMapList { get; set; }

        public string Sr { get; set; }

    }
}

Patvin_Live/MvcApplication1/Models/ContactUs.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Patvin.Models
{
    public class ContactUs
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Name is required.")]
        public string FullName { get; set; }

        [Required(ErrorMessage = "Email address is required.")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "Invalid email address.")]
        public string Email { get; set; }


        [Required(ErrorMessage = "Phone number is required.")]
        [DataType(DataType.PhoneNumber)]
        [StringLength(10)]
        //[RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Enter a valid mobile number.")]
        [RegularExpression("^[0 - 9]{10}$|^[0-9]{10,12}$", ErrorMessage = "Enter a valid mobile number.")]
        public string ContactNo { get; set; }

        [Required(ErrorMessage = "Select any one Subject.")]
        public string Subject { get; set; }

        [Required(ErrorMessage = "Message is required.")]
        public string Comment { get; set; }

        public string ApplyDate { get; set; }

        public string Sr { get; set; }

        public List<ContactUs> ContactUsList { get; set; }

    }
}

Patvin_Live/MvcApplication1/Controllers/AdminController.cs
using Patvin.Authentication;
using Patvin.Models;
using ClosedXML.Excel;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace Patvin.Controllers
{
    [CustomAdminAccessFilter]
    public class AdminController : Controller
    {
        //
        // GET: /BillingDashboard/
        Utility util = new Utility();

        #region xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx --- Admin Index --- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

        public ActionResult Index()
        {
            var count = Counting();
            ViewBag.CaseStudy = count["CaseStudy"].ToString();
            ViewBag.ApplyForJob = count["ApplyForJob"].ToString();
            ViewBag.ContactUs = count["ContactUs"].ToString();
            ViewBag.GetInTouch = count["GetInTouch"].ToString();
            return View();
        }

        public Dictionary<string, string> Counting()
        {
            Dictionary<string, string> objDic = new Dictionary<string, string>();
            StringBuilder strbuil = new StringBuilder();
            DataSet ds = new DataSet();
            ds = util.Display1("Exec Proc_CMS 'adminIndexCount'");
            if (ds.Tables.Count > 0)
            {
                //Case Study
                objDic.Add(ds.Tables[0].Rows[0]["Tbl"].ToString(), ds.Tables[0].Rows[0]["Count"].ToString());

                //ApplyForJob
                objDic.Add(ds.Tables[1].Rows[0]["Tbl"].ToString(), ds.Tables[1].Rows[0]["Count"].ToString());

                //ContactUs
                objDic.Add(ds.Tables[2].Rows[0]["Tbl"].ToString(), ds.Tables[2].Rows[0]["Count"].ToString());

                //Get In Touch
                objDic.Add(ds.Tables[3].Rows[0]["Tbl"].ToString(), ds.Tables[3].Rows[0]["Count"].ToString());
            }
            return objDic;
        }

        #endregion


        #region xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx--- Admin Profile Section Start---xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        public ActionResult UpdateProfile()
        {
            DataTable dt = GetAdminDataForProfileUpdate();
            Login log = new Login();

            log.Id = dt.Rows[0]["Id"].ToString();
            log.Name = dt.Rows[0]["Name"].ToString();
            log.Emailid = dt.Rows[0]["Emailid"].ToString();
            log.Mobileno = dt.Rows[0]["Mobileno"].ToString();
            return View(log);
        }

        public DataTable GetAdminDataForProfileUpdate()
        {
            DataTable dt = new DataTable();
            try
            {
                dt = util.Display("Execute Proc_SuperAdminLogin 'GETDETAIL_FOR_UPDATE'");
            }
            catch (Exception ex)
            {

                throw ex;
            }
            return dt;
        }

        [HttpPost]
        public JsonResult UpdateProfile(Login logobj)
        {
            var response = "";

            try
            {
                response = UpdateProfileDetails(logobj.Id, logobj.Name, logobj.Emailid, logobj.Mobileno);
            }
            catch
            {
                response = "";
            }
            string Url = string.Empty;
            string Responsetype = response == "" ? "Fail" : "Success";

            return Json(new { Responsetype = Responsetype }, JsonRequestBehavior.AllowGet);
        }

        public string UpdateProfileDetails(string id, string name, string emailid, string mobileno)
        {
            string Response = string.Empty;
            try
            {
                using (SqlCommand cmd = new SqlCommand("Proc_SuperAdminLogin"))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@PARA", "UPDATEPROFILEDETAILS");
                    cmd.Parameters.AddWithValue("@NAME", name);
                    cmd.Parameters.AddWithValue("@EMAILID", emailid);
                    cmd.Parameters.AddWithValue("@MOBILENO", mobileno);
                    cmd.Parameters.AddWithValue("@ID", id);
                    if (util.Execute(cmd))
                    {
                        Response = "success";
                    }
                    else
                    {
                        Response = "";
                    }
                }
            }
            catch
            {

                Response = "";
            }
            return Response;
        }


        public ActionResult ChangePassword()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ChangePassword(Login obj)
        {
            using (SqlCommand cmd = new SqlCommand("Proc_SuperAdminLogin"))
            {
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@PARA", "CHANGE_PASSWORD");
                cmd.Parameters.AddWithValue("@USERNAME", Request.Cookies["SuperAdminusername"].Value);
                cmd.Parameters.AddWithValue("@PASSWORD", obj.OldPassword);
                cmd.Parameters.AddWithValue("@NEWPASSWORD", obj.Password);
                DataTable dt = new DataTable();
                dt = util.Display(cmd);
                if (dt.Rows[0]["update"].ToString() == "correct")
                {
                    ViewBag.message = "Success";
                    ViewBag.message1 = "Your Password has been changed Successfully!";
                }
                else
                {
                    ViewBag.message = "fail";
                    ViewBag.message1 = "Sorry ! Password Could not be changed Successfully!";
                }
                ModelState.Clear(); //make blank to class property
            }
            return View();
        }

        #endregion xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx--- Billing Profile Section End---xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

        #region xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx -- Home Banner --- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

        public ActionResult HomeBanner()
        {
            HomeBanner objHomeBanner = new HomeBanner();
            objHomeBanner.HomeBannerList = GetHomeBannerList();
            return View(objHomeBanner);
        }

        public List<HomeBanner> GetHomeBannerList()
        {
            try
            {
                List<HomeBanner> objHomeBanner = new List<HomeBanner>();
                DataTable dt = new DataTable();
                dt = util.Display("Execute Proc_Banner 'get'");
                if (dt.Rows.Count > 0)
                {
                    foreach (DataRow dr in dt.Rows)
                    {
                        HomeBanner banner = new HomeBanner();
                        banner.Sr = dr["Sr"].ToString();
                        banner.BannerId = int.Parse(dr["BannerId"].ToString());
                        banner.Image = dr["Image"].ToString();
                        banner.BannerText1 = dr["BannerText1"].ToString();
                        banner.BannerText2 = dr["BannerText2"].ToString();
                        banner.BannerText3 = dr["BannerText3"].ToString();
                        banner.DisplayOrder = int.Parse(dr["DisplayOrder"].ToString());
                        banner.Url = dr["Url"].ToString();
                        banner.Img_Alt_Tag = dr["Img_Alt_Tag"].ToString();

                        objHomeBanner.Add(banner);
                    }
                }
                return objHomeBanner;
            }
            catch (Exception ex)
            {
                LogError log = new LogError();
                log.HandleException(ex);

                ViewBag.Message = "error";
                ViewBag.Message1 = "Try again after some time.";

                TempData["Message"] = ViewBag.Message;
                TempData["Message1"] = ViewBag.Message1;

                return null;
            }
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult HomeBanner(HomeBanner objHomeBanner, HttpPostedFileBase[] Image)
        {
            try
            {
                if (objHomeBanner.BannerId != 0)
                {
                    ModelState.Remove("Image");
                }

                if (ModelState.IsValid)
                {
                    string VirtualFile = "~/Content/uploads/HomeBanner/";
                    string Img = string.Empty;

                    if (Image != null)
                    {
                        foreach (HttpPostedFileBase file in Image)
                        {
                            //string MainFile = string.Empty;
                            //Checking file is available to save.  
                            if (file != null)
                            {
                                string ext = Path.GetExtension(file.FileName).ToLower();
                                if (!util.IsValidImageFileExtension(ext))
                                {
                                    ViewBag.Message = "warning";
                                    ViewBag.Message1 = "Only jpg/jpeg and png files are allowed!";

                                    TempData["Message"] = ViewBag.Message;
                                    TempData["Message1"] = ViewBag.Message1;
                                    return RedirectToAction("HomeBanner");
                                }
                                else
                                {
                                    //MainFile = util.GetUniqueName(VirtualFile, "BlogImg", ".jpg", null, false); //Get Unique Name  
                                    //string  MainFile = "BlogImg-" + DateTime.Now.ToString("yyyymmddMMss") + System.IO.Path.GetExtension(file.FileName);
                                    var fileName = "Banner-" + Guid.NewGuid().ToString() + System.IO.Path.GetExtension(file.FileName);

Patvin_Live/MvcApplication1/Views/Admin/ApplyForJob.cshtml
@model Patvin.Models.ApplyForJob
@{
    ViewBag.Title = "ApplyForJob";
    Layout = "~/Views/Shared/AdminMaster.cshtml";
}

<div class="right_col" role="main">
    <div class="">

        <div class="page-title">
            <div class="title_left">
                <h3>Applying For Job List</h3>
            </div>

 
        </div> 
        <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_content">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>Sr No.</th>
                                    <th>
                                        Name
                                    </th>
                                    <th>
                                        Email
                                    </th>                                    
                                    <th>
                                        Role
                                    </th>
                                    <th>
                                        Contact No
                                    </th>
                                    <th>
                                        Resume
                                    </th>
                                    <th>
                                        Apply Date
                                    </th>
                                    <th>Delete</th>
                                </tr>
                            </thead>

                            <tbody>

                                @if (Model.ApplyForJobList != null)
                                {
                                    foreach (var item in Model.ApplyForJobList)
                                    {
                                        <tr class="counter">
                                            <td>@Html.DisplayFor(modelItem => item.Sr)</td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Name)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Email)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Role)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.ContactNo)
                                            </td>
                                            <td>
                                                <a href="~/Content/uploads/Resume/@item.Resume" target="_blank">View Resume</a>
                                                @*@Html.DisplayFor(modelItem => item.Resume)*@
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.ApplyDate)
                                            </td>

                                            <td>

                                                <a href="@Url.Action("DeleteApplyForJob", "Admin", new { id = item.Id })" title="Delete" onclick="return confirm('Are you sure you want to delete this Record?')">
                                                    <button type="button" class="btn ">
                                                        <i class="fa fa-close"></i>
                                                    </button>
                                                </a>

                                            </td>
                                        </tr>
                                    }
                                }

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Patvin_Live/MvcApplication1/Views/Admin/CasestudyformRegister.cshtml
@model Patvin.Models.Casestudyform

@{
    ViewBag.Title = "CasestudyformRegister";
    Layout = "~/Views/Shared/AdminMaster.cshtml";
}


<div class="right_col" role="main">
    <div class="">

        <div class="page-title">
            <div class="title_left">
                <h3>Case Study Register</h3>
            </div>

         @*   <div class="title_right">
                <div class="col-md-12 col-sm-12 col-xs-12 form-group pull-right top_search">
                    <div class="input-group pull-right">

                        <span class="input-group-btn"></span>

                        <a href="@Url.Action("AppyForJobExportData", "Admin")">
                            <div class="fa-hover col-md-12 col-sm-12 btn btn-success exporttoexcel">
                                Export to <i class="fa fa-file-excel-o fa-1x" aria-hidden="true"></i>
                            </div>
                        </a>

                    </div>

                </div>
            </div>*@
        </div> 
        <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_content">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>Sr No.</th>
                                     <th>
                                        Title
                                    </th>
                                    <th>
                                        Name
                                    </th>
                                     <th>
                                        Company Name
                                    </th>
                                    <th>
                                        Email
                                    </th>                                    

                                    <th>
                                        Apply Date
                                    </th>
                                    <th>Delete</th>
                                </tr>
                            </thead>

                            <tbody>

                                @if (Model.CasestudyformList != null)
                                {
                                    foreach (var item in Model.CasestudyformList)
                                    {
                                        <tr class="counter">
                                            <td>@Html.DisplayFor(modelItem => item.Sr)</td>
                                                 <td>
                                                @Html.DisplayFor(modelItem => item.Title)
                                            </td>  
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Name)
                                            </td>
                                                <td>
                                                @Html.DisplayFor(modelItem => item.CompanyName)
                                            </td>  
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Email)
                                            </td>                                                                                                               
                                            <td>
                                                @Html.DisplayFor(modelItem => item.ApplyDate)
                                            </td>

                                            <td>

                                                <a href="@Url.Action("DeleteCasestudyformRegister", "Admin", new { id = item.caseId })" title="Delete" onclick="return confirm('Are you sure you want to delete this Record?')">
                                                    <button type="button" class="btn ">
                                                        <i class="fa fa-close"></i>
                                                    </button>
                                                </a>

                                            </td>
                                        </tr>
                                    }
                                }

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>