Patvin_Live/MvcApplication1/Models/Casestudyform.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Patvin.Models
{
    public class Casestudyform
    {
        public int caseId { get; set; }

        public string Title { get; set; }

        [Required(ErrorMessage ="Name is required")]
        public string Name { get; set;}

        [Required(ErrorMessage = "Company Name is required")]
        public string CompanyName { get; set; }

        [Required(ErrorMessage = "Email address is required.")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "Invalid email address.")]
        public string Email { get; set; }


        public string ApplyDate { get; set; }

        public string Sr { get; set; }

        public List<Casestudyform> CasestudyformList { get; set; }

    }
}

Patvin_Live/MvcApplication1/Models/ContactUs.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Patvin.Models
{
    public class ContactUs
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Name is required.")]
        public string FullName { get; set; }

        [Required(ErrorMessage = "Email address is required.")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "Invalid email address.")]
        public string Email { get; set; }


        [Required(ErrorMessage = "Phone number is required.")]
        [DataType(DataType.PhoneNumber)]
        [StringLength(10)]
        //[RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Enter a valid mobile number.")]
        [RegularExpression("^[0 - 9]{10}$|^[0-9]{10,12}$", ErrorMessage = "Enter a valid mobile number.")]
        public string ContactNo { get; set; }

        [Required(ErrorMessage = "Select any one Subject.")]
        public string Subject { get; set; }

        [Required(ErrorMessage = "Message is required.")]
        public string Comment { get; set; }

        public string ApplyDate { get; set; }

        public string Sr { get; set; }

        public List<ContactUs> ContactUsList { get; set; }

    }
}

Patvin_Live/MvcApplication1/Models/GetInTouchForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Patvin.Models
{
    public class GetInTouchForm
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Name is required.")]
        public string FullName { get; set; }

        [Required(ErrorMessage = "Email address is required.")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "Invalid email address.")]
        public string Email { get; set; }


        [Required(ErrorMessage = "Phone number is required.")]
        [DataType(DataType.PhoneNumber)]
        [StringLength(10)]
        //[RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Enter a valid mobile number.")]
        [RegularExpression("^[0 - 9]{10}$|^[0-9]{10,12}$", ErrorMessage = "Enter a valid mobile number.")]
        public string ContactNo { get; set; }


        [Required(ErrorMessage = "Message is required.")]
        public string Comment { get; set; }

        public string ApplyDate { get; set; }

        public string Sr { get; set; }

        public List<GetInTouchForm> GetInTouchFormList { get; set; }
    }
}

Patvin_Live/MvcApplication1/Models/Management.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Patvin.Models
{
       public class Management
        {
            public int Id { get; set; }

            [Required(ErrorMessage = "Heading is Required.")]
            public string Heading { get; set; }

            [Required(ErrorMessage = "Description is Required ")]
            public string Description { get; set; }
            public int DisplayOrder { get; set; }

            [Required(ErrorMessage = "Image is required.")]
            public string Image { get; set; }
            public List<Management> ManagementList { get; set; }

            public string Sr { get; set; }

            public string imgPreview { get; set; }

        [Required(ErrorMessage = "Designation is Required.")]
        public string Designation { get; set; }

        public string Img_Alt_Tag { get; set; }

    }
    }

Patvin_Live/MvcApplication1/Models/NewsRoom.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Patvin.Models
{
    public class NewsRoom
    {
        public int NewsId { get; set; }

        [Required(ErrorMessage = "Select any one type.")]
        public string Type { get; set; }

        [Required(ErrorMessage = "Title is required.")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Image is required.")]
        public string Image { get; set; }

        [Required(ErrorMessage = "Date is required.")]
        public string Date { get; set; }

        [Required(ErrorMessage = "Description is required.")]
        public string Description { get; set; }

        public string imgPreview { get; set; }

        public string Sr { get; set; }
        public List<NewsRoom> NewsRoomList { get; set; }

        public string Slug { get; set; }

        public string Img_Alt_Tag { get; set; }

        public string Category { get; set; }

    }
}

Patvin_Live/MvcApplication1/Models/OurValues.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Patvin.Models
{
    public class OurValues
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Heading is Required.")]
        public string Heading { get; set; }

        [Required(ErrorMessage = "Description is Required ")]
        public string Description { get; set; }
        public int DisplayOrder { get; set; }

        [Required(ErrorMessage = "Image is required.")]
        public string Image { get; set; }
        public List<OurValues> OurValuesList { get; set; }

        public string Sr { get; set; }

        public string imgPreview { get; set; }

        public string Img_Alt_Tag { get; set; }

    }
}

Patvin_Live/MvcApplication1/Models/Services.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Patvin.Models
{
    public class Services
    {

       public int ServId { get; set; }

        [Required(ErrorMessage = "Title is required")]
        public string Title { get; set; } 

        [Required(ErrorMessage = "Description is Required ")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Icon is required")]
        public string Icon { get; set; }

        [Required(ErrorMessage ="Image is required")]
        public string Image { get; set; }

        public string iconPreview { get; set; }

        public string imgPreview { get; set; }

        public string Sr { get; set; }

        public List<Services> ServicesList { get; set; }

        public string Img_Alt_Tag { get; set; }
        public string Icon_Alt_Tag { get; set; }
    }
}

Patvin_Live/MvcApplication1/Controllers/WebsiteController.cs
using Patvin.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace Patvin.Controllers
{
    public class WebsiteController : Controller
    {
        //
        // GET: /Website/
        Utility util = new Utility();

        #region Home Page
        public ActionResult Index()
        {
            TempData["Menu"] = "Home";
            string title = "/";
            ViewBag.Title = UpdateMetaDetails(title);

            ViewBag.Banner = HomeBanner();
            ViewBag.WorldClassSolutions = CMS(1);
            ViewBag.WorldClassSolutionspartners = WorldClassSolutionspartners();
            ViewBag.AboutPatvin = CMS(2);
            ViewBag.IndustrialSolutions = CMS(3);
            ViewBag.HomeStatistics = HomeStatistics();
            ViewBag.HomeIndustries = HomeIndustries();
            ViewBag.GreenWorld = GreenWorld();
            ViewBag.ProductSolutions = ProductSolutions();
            ViewBag.HomeServices = HomeServices();


            return View();
        }

        public string HomeBanner()
        {
            string response = "";
            StringBuilder strBuild = new StringBuilder();
            DataTable dt = new DataTable();
            dt = util.Display("Exec Proc_Banner 'bindBanner'");
            if (dt.Rows.Count > 0)
            {
                //int count = 1;
                foreach (DataRow dr in dt.Rows)
                {
                    //if (count == 1)
                    //{
                    strBuild.Append("<div class='slide' style='background-image:url(/Content/uploads/HomeBanner/" + dr["Image"].ToString() + ");'>");
                    strBuild.Append("<div class='maxWidth textSlide'>");
                    strBuild.Append("<div class='text_1'>" + dr["BannerText1"].ToString() + "</div>");
                    strBuild.Append("<div class='text_2'>" + dr["BannerText2"].ToString() + "</div>");
                    strBuild.Append("<p class='text_3'>" + dr["BannerText3"].ToString() + "</p>");
                    strBuild.Append("<div class='slideBtn'>");
                    strBuild.Append("<a href='" + dr["Url"].ToString() + "' class='orangeBtn'>Learn more</a>");
                    strBuild.Append("</div>");
                    strBuild.Append("</div>");
                    strBuild.Append("</div>");
                    //}
                    //else
                    //{
                    //    strBuild.Append("<div class='slide' style='background-image:url(/Content/uploads/HomeBanner/" + dr["Image"].ToString() + ");'>");
                    //    strBuild.Append("<div class='maxWidth textSlide'>");
                    //    strBuild.Append("<div class='text_1'>" + dr["BannerText1"].ToString() + "</div>");
                    //    strBuild.Append("<div class='text_2'>" + dr["BannerText2"].ToString() + "</div>");
                    //    strBuild.Append("<p class='text_3'>" + dr["BannerText2"].ToString() + "</p>");
                    //    strBuild.Append("<div class='slideBtn'>");
                    //    strBuild.Append("<a href = 'class='orangeBtn''>Learn more</a>");
                    //    strBuild.Append("</div>");
                    //    strBuild.Append("</div>");
                    //    strBuild.Append("</div>");
                    //}
                    //count++;
                }
                response = strBuild.ToString();
            }
            return response;
        }

        public string WorldClassSolutionspartners()
        {
            string response = "";
            StringBuilder strBuild = new StringBuilder();
            DataTable dt = new DataTable();
            dt = util.Display("Exec Proc_HomeSolutions 'bindHomeSolutions'");
            if (dt.Rows.Count > 0)
            {
                foreach (DataRow dr in dt.Rows)
                {

                    strBuild.Append("<div class=''>");
                    strBuild.Append("<div class='clogoBox fade_anim'>");
                    strBuild.Append("<img src = '/Content/uploads/HomeSolutions/" + dr["Image"].ToString() + "' alt='"+ dr["Img_Alt_Tag"].ToString() + "' > ");
                    strBuild.Append("</div>");
                    strBuild.Append("</div>");
                }
                response = strBuild.ToString();

            }
            return response;
        }

        public string HomeStatistics()
        {
            string response = "";
            StringBuilder strBuild = new StringBuilder();
            DataTable dt = new DataTable();
            dt = util.Display("Exec Proc_HomeStatistic 'bindHomeStatistics'");
            if (dt.Rows.Count > 0)
            {
                foreach (DataRow dr in dt.Rows)
                {

                    strBuild.Append("<div class='statisticHolder' id='counter' >");
                    strBuild.Append("<div class='iconBox'>");
                    strBuild.Append("<span><i class='" + dr["Icon"].ToString() + "'></i></span>");
                    strBuild.Append("</div>");
                    strBuild.Append("<div class='iconTxt'><strong class='titillium'><span class='counter' data-count=" + dr["Counting"].ToString() + ">0</span>+</strong>" + dr["Description"].ToString() + "</div> ");
                    strBuild.Append("</div>");

                }
                response = strBuild.ToString();

            }
            return response;
        }

        public string HomeIndustries()
        {
            string response = "";
            StringBuilder strBuild = new StringBuilder();
            DataTable dt = new DataTable();
            dt = util.Display("Exec Proc_HomeIndustries 'bindHomeIndustries'");
            if (dt.Rows.Count > 0)
            {
                foreach (DataRow dr in dt.Rows)
                {

                    strBuild.Append("<a href ='" + dr["Url"].ToString() + "' class='col-lg-3 col-sm-4 col-6'>");
                    strBuild.Append("<img src ='/Content/uploads/HomeIndustries/" + dr["Icon"].ToString() + "' alt='"+ dr["Img_Alt_Tag"].ToString() + "'>");
                    strBuild.Append("<h3>" + dr["Heading"].ToString() + "</h3>");
                    strBuild.Append("</a>");

                }
                response = strBuild.ToString();

            }
            return response;
        }

        public string GreenWorld()
        {
            string response = "";
            StringBuilder strBuild = new StringBuilder();
            DataTable dt = new DataTable();
            dt = util.Display("Exec Proc_HomeGreenWorld 'bindHomeGreenWorld'");
            if (dt.Rows.Count > 0)
            {
                foreach (DataRow dr in dt.Rows)
                {

                    strBuild.Append("<div class='row'>");
                    strBuild.Append("<div class='col-sm-6 col-md-7 wc_text whiteColor'>");
                    strBuild.Append("<div class='title whiteColor'>");
                    strBuild.Append("<h4>We believe in a</h4>");
                    strBuild.Append("<h2 class='titillium'><strong>Green World</strong></h2>");
                    strBuild.Append("</div>");
                    strBuild.Append("<p>" + dr["Descrption"].ToString() + "</p><a href='/green-initiatives'>Read More <i class='fas fa-chevron-circle-right'></i></a>");
                    strBuild.Append("</div>");
                    strBuild.Append("<div class='col-sm-6 col-md-5 wc_img'>");
                    strBuild.Append("<div class='wcImg_holder' style='background-image:url(/Content/uploads/Images/" + dr["Image"].ToString() + ")'>");
                    strBuild.Append("</div>");
                    strBuild.Append("</div>");
                    strBuild.Append("</div>");
                }
                response = strBuild.ToString();

            }
            return response;
        }

        public string ProductSolutions()
        {
            string response = "";
            StringBuilder strBuild = new StringBuilder();
            DataTable dt = new DataTable();
            dt = util.Display("Exec Proc_HomeProductSolutions 'bindHomeProductSolutions'");
            if (dt.Rows.Count > 0)
            {

                foreach (DataRow dr in dt.Rows)
                {

                    //strBuild.Append("<div class='col-lg-3 col-sm-6 col-12'>");
                    strBuild.Append("<div>");
                    strBuild.Append("<div class='prod_box fade_anim'>");
                    strBuild.Append("<div class='prod_img'><img src='/Content/Uploads/Images/" + dr["Image"].ToString() + "' alt='" + dr["Img_Alt_Tag"].ToString() + "'></div>");
                    strBuild.Append("<div class='prod_info fade_anim'>");
                    strBuild.Append(" <a href=" + dr["Url"].ToString() + "><h2 class='titillium prodTitle'>" + dr["title"].ToString() + "</h2></a>");
                    strBuild.Append(" <p>" + dr["Description"].ToString() + "</p>");
                    strBuild.Append("<a href=" + dr["Url"].ToString() + " class='readmore'>Read more <i class='fas fa-chevron-circle-right'></i></a>");
                    strBuild.Append("</div>");
                    strBuild.Append("</div>");
                    strBuild.Append("</div>");
                    //strBuild.Append("</div>");
                }
                response = strBuild.ToString();
            }
            return response;
        }

        public string HomeServices()
        {

            string response = "";
            StringBuilder strBuild = new StringBuilder();
            DataTable dt = new DataTable();
            dt = util.Display("Exec Proc_Services 'bindHomeServices'");
            if (dt.Rows.Count > 0)
            {

                foreach (DataRow dr in dt.Rows)
                {
                    string sluglink = dr["Title"].ToString();

Patvin_Live/MvcApplication1/Views/Website/CaseStudyListing.cshtml
@model Patvin.Models.Casestudyform
@using System.Web.Optimization

@{
   
    Layout = "~/Views/Shared/WebsiteMaster.cshtml";
}


@section metatags{
    @Html.Raw(ViewBag.Title)

}

<div class="mainContainer container-fluid">

    @*corona message*@
    <div class="row msgAlert">
        <div class="maxWidth">
            <p style="margin-bottom:0;">
                Our Team looks forward to Serving you once this COVID-19 Pandemic subsides, till then stay safe & healthy.
                @*<a href="~/Content/uploads/PATVIN Health Advisory.pdf" target="_blank">Patvin Health Advisory</a>*@
            </p>
        </div>
    </div>

    <div class="row innerPageBanner">

        <div class="inpageImg" style="background-image:url(/Content/uploads/InnerBanner/@ViewBag.InnerBanner">

            <div class="maxWidth">
                <div class="pageTitle text-center">
                    <div class="breadcrums"><a href="~/">Home</a><a>Products & Solutions</a></div>
                    <h1>Case Studies</h1>
                </div>
            </div>

        </div>

    </div>

    <div class="row pageContent">
        <div class="container-fluid">
            <div class="maxWidth solnListSection mt-5">
                <div class="fade_anim">

                    <div class="row">

                        @Html.Raw(ViewBag.BindCaseStudyListing)

                    </div>

                    <div class="d-none">

                        <div class="csForm downloadbgicon px-4 px-sm-5 py-4" id="case_study_form">

                            <div class="csfContent">
                                <div class="csfTitle titillium orangeColor"><h2>Register to Download</h2></div>

                                <div class="csf_dwnload">
                                    <span id="spnTitle"></span>

                                    @*@Html.Raw(ViewBag.Title);*@
                                </div>

                                <p>Enter the details below to download the case study.</p>


                                @using (@Html.BeginForm("CaseStudyListing", "Website", FormMethod.Post))
                                {
                                    @Html.HiddenFor(m => m.Title, new { @Id = "Title" })

                                    <div class="form-group">
                                        @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Name", @autocomplete = "off" })
                                        @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="form-group">
                                        @Html.TextBoxFor(m => m.CompanyName, new { @class = "form-control", placeholder = "Company Name", @autocomplete = "off" })
                                        @Html.ValidationMessageFor(m => m.CompanyName, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="form-group">
                                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email Address", @autocomplete = "off" })
                                        @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="w-100 pt-3"></div>

                                    <div class="form-group">
                                        <button type="submit" class="orangeBtn">Send Request</button>
                                    </div>

                                }

                            </div>

                        </div>

                        <div class="csForm downloadbgicon px-4 px-sm-5 py-4" id="case_study_form1">

                            <div class="csfContent">
                                <div class="csfContent text-center pt-5">
                                    <div class="csfTitle titillium orangeColor"><h2>Thank You!</h2></div>

                                    <p>We will send you an email with the requested case study. </p>

                                </div>


                            </div>

                        </div>

                    </div>

                </div>

            </div>

        </div>


    </div>



    @if (TempData["Message"] != null)
    {
        if (TempData["Message"].ToString() == "success")
        {
            <script>
                $(document).ready(function () {

                    $("#case_study_form1").fancybox().trigger('click');

                })
            </script>
        }
    }

</div>



@Scripts.Render("~/Admin/FormValidation")


    <script>
        function RoleSelected(role) {
            //alert(role);
            jQuery('#spnTitle').html(role);
            $('#Title').val(role);

        }
        



    </script>

Patvin_Live/MvcApplication1/Views/Website/Casestudyform.cshtml
@model Patvin.Models.Casestudyform

@{
    Layout = null;
}

<!DOCTYPE html>

@*<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Casestudyform</title>
</head>
<body>
    <div>
        
    </div>
</body>
</html>*@

<div class="csForm downloadbgicon px-4 px-sm-5 py-4">

    <div class="csfContent">
        <div class="csfTitle titillium orangeColor"><h2>Register to Download</h2></div>

        <div class="csf_dwnload">@Html.LabelFor(m=>m.Title)</div>

        <p>Enter the details below to download the case study.</p>

       @using (@Html.BeginForm("Casestudyform", "Website", FormMethod.Post))
       {

            <div class="form-group">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Name", @autocomplete = "off" })
                @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.TextBoxFor(m => m.CompanyName, new { @class = "form-control", placeholder = "Company Name", @autocomplete = "off" })
                @Html.ValidationMessageFor(m => m.CompanyName, "", new { @class = "text-danger" })         
            </div>

            <div class="form-group">
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email Address", @autocomplete = "off" })
                @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })             
            </div>

            <div class="w-100 pt-3"></div>

            <div class="form-group">
                <button type="submit" class="orangeBtn">Send Request</button>
            </div>

       }

    </div>


</div>

Patvin_Live/MvcApplication1/Views/Website/HeaderMenu.cshtml
<header class="container-fluid fade_anim sina-nav mobile-sidebar navbar-fixed" data-top="150">
    <div class="row topHeader fade_anim">

        <div class="maxWidth opensans">

            <div class="row">
                <div class="col">
                    <div class="brandTagline"><img src="/Content/Resource/website/images/tagline.png" title="Your Partner for Quality..." alt="your partner for quality"></div>
                </div>
                <div class="col">
                    <div class="searchbox">
                        @*<input type="text" placeholder="Search">*@
                        <input type="text" id="txtSearch" placeholder="Search">
                        <button><i class="fas fa-search" onclick="MobSearchKeyword()"></i></button>

                    </div>
                </div>
            </div>

            <!--<div class="loginBox titillium"><a href="" class="orangeBtn"><strong>Login</strong></a></div>

            <div class="top_social">
                <ul>
                <li><a href="" title="Facebook"><span class="fab fa-facebook-f"></span></a></li>
                <li><a href="" title="Twitter"><span class="fab fa-twitter"></span></a></li>
                <li><a href="" title="YouTube"><span class="fab fa-youtube"></span></a></li>
                <li><a href="" title="LinkedIn"><span class="fab fa-linkedin-in"></span></a></li>
                </ul>
            </div>-->
        </div>

    </div>

    <div class="row bottomHeader">

        <div class="maxWidth">
            <div class="logo fade_anim"><a href="~/"><img src="/Content/Resource/website/images/logo.jpg" alt="Patvin logo"></a></div>

            <div class="menuBox no_anim titillium collapse navbar-collapse" id="navbar-menu">

                <ul class="sina-menu no_anim" data-in="fadeInUp" data-out="fadeOutDown">

                    <li class="@Html.Raw(ViewBag.ActiveMenu == "Home"?"active":"")"><a href="~/">Home</a></li>

                    <li class='@Html.Raw(ViewBag.ActiveMenu == "WhoWeAre"?"dropdown active":ViewBag.ActiveMenu =="Management"?"dropdown active":ViewBag.ActiveMenu =="OurValues"?"dropdown active":ViewBag.ActiveMenu =="HealthSafety"?"dropdown active":"dropdown")'>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">About Us</a>
                        <ul class="dropdown-menu">
                            <li class='@Html.Raw(ViewBag.ActiveMenu == "WhoWeAre"?"active":"")'><a href="~/WhoWeAre">Who We Are </a></li>
                            <li class='@Html.Raw(ViewBag.ActiveMenu == "Management"?"active":"")'><a href="~/LeadershipTeam">Leadership Team</a></li>
                            <li class='@Html.Raw(ViewBag.ActiveMenu == "OurValues"?"active":"")'><a href="~/OurValues">Our Values</a></li>
                            <li class='@Html.Raw(ViewBag.ActiveMenu == "HealthSafety"?"active":"")'><a href="~/HealthSafety">Health & Safety </a></li>
                        </ul>
                    </li>

                    <li class="@Html.Raw(ViewBag.ActiveMenu == "products"?"dropdown active":ViewBag.ActiveMenu =="Solutions"?"dropdown active":ViewBag.ActiveMenu =="Technology"?"dropdown active":ViewBag.ActiveMenu =="CaseStudyListing"?"dropdown active":ViewBag.ActiveMenu =="Testimonials"?"dropdown active":"dropdown")">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Products & Solutions</a>
                        <ul class="dropdown-menu">
                            <li class="@Html.Raw(ViewBag.ActiveMenu == "products"?"active":"")"><a href="~/products">Products</a></li>
                            <li class="@Html.Raw(ViewBag.ActiveMenu == "Solutions"?"dropdown active":"dropdown")">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Solutions</a>
                                <ul class="dropdown-menu">
                                    @Html.Raw(ViewBag.Solutions)
                                </ul>
                            </li>
                            <li class="@Html.Raw(ViewBag.ActiveMenu == "Technology"?"dropdown active":"dropdown")">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Technology</a>
                                <ul class="dropdown-menu">
                                    @*<li><a href="~/website/Automation">Automation</a></li>
                                        <li><a href="#">Industrie 4.0 </a></li>
                                        <li><a href="#">Human Robot Collaboration</a></li>*@
                                    @Html.Raw(ViewBag.Technology)
                                </ul>
                            </li>
                            <li class="@Html.Raw(ViewBag.ActiveMenu == "CaseStudyListing"?"active":"")" ><a href="~/CaseStudyListing">Case Studies</a></li>
                            <li class="@Html.Raw(ViewBag.ActiveMenu == "Testimonials"?"active":"")"><a href="~/Testimonials">Testimonials</a></li>
                        </ul>
                    </li>

                    <li class="@Html.Raw(ViewBag.ActiveMenu == "Collaborative Robots"?"dropdown active":"dropdown")">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Collaborative Robots</a>
                        <ul class="dropdown-menu">
                            @Html.Raw(ViewBag.CollaborativeRobots)
                            <li class="@Html.Raw(ViewBag.ActiveMenu == "Blogs"?"active":"")"><a href="~/Blogs">Blogs</a></li>
                        </ul>
                    </li>

                    <li class="@Html.Raw(ViewBag.ActiveMenu == "Services"?"dropdown active":"dropdown")">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Services</a>
                        <ul class="dropdown-menu">
                            @Html.Raw(ViewBag.ServicesMenu)
                        </ul>
                    </li>

                    <li class="@Html.Raw(ViewBag.ActiveMenu == "Industries"?"dropdown active":"dropdown")">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Industries</a>
                        <ul class="dropdown-menu">
                            @Html.Raw(ViewBag.Industries)
                        </ul>
                    </li>

                    <li class="@Html.Raw(ViewBag.ActiveMenu == "Newsroom"?"active":"")"><a href="~/Newsroom">Newsroom</a></li>

                    <li class="@Html.Raw(ViewBag.ActiveMenu == "Careers"?"active":"")"><a href="~/Careers">Careers</a></li>

                    <li class="@Html.Raw(ViewBag.ActiveMenu == "ContactUs"?"active":"")"><a href="~/ContactUs">Contact Us</a></li>
                </ul>

            </div>

            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu"><i class="fa fa-bars"></i></button>

        </div>

    </div>


    @*<script>
        $(document).ready(function () {
            $('ul li').click(function () {
                alert($(this).text());
                $('ul li').removeClass("active");
                $(this).addClass("active");
            });
            });
        </script>*@

</header>